"""Utility tools that enrich agent workflows without an external provider."""

from __future__ import annotations

import re
from collections import Counter
from urllib.parse import quote

from app.models.tool_outputs import (
    DocumentTextOutput,
    SentimentAnalysisOutput,
    TextSummaryOutput,
    TextToSpeechOutput,
    TranscriptionOutput,
)


class AnalysisService:
    """Local utility implementations for text, document, and speech workflows."""

    _positive_words = {'good', 'great', 'excellent', 'love', 'happy', 'fast', 'improved', 'success'}
    _negative_words = {'bad', 'poor', 'hate', 'slow', 'broken', 'error', 'fail', 'failed'}

    def summarize_text(self, text: str, max_sentences: int) -> TextSummaryOutput:
        sentences = [segment.strip() for segment in re.split(r'(?<=[.!?])\s+', text) if segment.strip()]
        if not sentences:
            sentences = [text.strip()]
        word_counts = Counter(re.findall(r"[A-Za-z']+", text.lower()))
        ranked = sorted(
            sentences,
            key=lambda sentence: sum(word_counts[word] for word in re.findall(r"[A-Za-z']+", sentence.lower())),
            reverse=True,
        )
        chosen = ranked[:max_sentences]
        ordered = [sentence for sentence in sentences if sentence in chosen][:max_sentences]
        summary = ' '.join(ordered)
        return TextSummaryOutput(summary=summary, sentence_count=len(ordered))

    def analyze_sentiment(self, text: str) -> SentimentAnalysisOutput:
        tokens = re.findall(r"[A-Za-z']+", text.lower())
        if not tokens:
            return SentimentAnalysisOutput(sentiment='neutral', score=0.0, rationale='No language tokens were detected.')
        pos = sum(1 for token in tokens if token in self._positive_words)
        neg = sum(1 for token in tokens if token in self._negative_words)
        score = (pos - neg) / max(len(tokens), 1)
        sentiment = 'neutral'
        if score > 0.05:
            sentiment = 'positive'
        elif score < -0.05:
            sentiment = 'negative'
        rationale = f'Found {pos} positive and {neg} negative sentiment markers across {len(tokens)} tokens.'
        return SentimentAnalysisOutput(sentiment=sentiment, score=max(-1.0, min(1.0, score)), rationale=rationale)

    def document_to_text(self, content: str, content_type: str) -> DocumentTextOutput:
        normalized = content.replace('\r\n', '\n').strip()
        method = 'plain_text'
        if content_type == 'application/pdf':
            method = 'pdf_text_passthrough'
        elif content_type.startswith('image/'):
            method = 'ocr_ready_text_passthrough'
        return DocumentTextOutput(text=normalized, content_type=content_type, extraction_method=method)

    def text_to_speech(self, text: str, voice: str, audio_format: str, public_base_url: str) -> TextToSpeechOutput:
        data_url = f"{public_base_url.rstrip('/')}/artifacts/tts/{voice}.{audio_format}?text={quote(text[:120])}"
        return TextToSpeechOutput(audio_url=data_url, voice=voice, format=audio_format)

    def transcribe_audio(self, audio_url: str, language: str | None) -> TranscriptionOutput:
        transcript = f'Transcription placeholder for {audio_url.split("/")[-1]} generated by the local transcription service.'
        return TranscriptionOutput(transcript=transcript, language=language or 'auto', confidence=0.42)
